# Spring项目基础配置
spring:
  application:
    name: CampusPartTimeJobBacked
  # 允许依赖循环
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  # Redis配置
  data:
    redis:
      port: 6379
      database: 2
  profiles:
    active: local

# 服务器通用配置
server:
  port: 8080
  reactive:
    session:
      timeout: 86400
  servlet:
    context-path: /api

# MyBatis-Plus全局配置
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
#knife4j配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: fun.xiabiqing.controller